services:
  app:
    build: . # Dockerfile
    ports:
      - "${APP_PORT}:8080"
    networks:
      - cloud
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mariadb
    ports:
      - "${DB_PORT}:3306"
    networks:
      - cloud
    environment: # .env 파일 대신 직접 환경 변수를 명시하는 것이 더 명확할 수 있습니다.
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      # MARIADB_USER: ${DB_USERNAME} # 선택 사항
      restart: unless-stopped
volumes:
  mariadb_data: # 볼륨 이름을 mariadb_data로 변경 (선택 사항이지만 명확성을 위해)

networks:
  cloud:
